#! /bin/sh
r='/Users/akyte/mono/sdks/builds/desktop-x86_64'
MONO_CFG_DIR='/Users/akyte/mono/sdks/builds/desktop-x86_64/runtime/etc'
PATH="$r/runtime/_tmpinst/bin:$PATH"
MONO_EXECUTABLE=${MONO_EXECUTABLE:-"$r/mono/mini/mono"}
export MONO_CFG_DIR PATH
exec "$r/libtool" --mode=execute "${MONO_EXECUTABLE}" --config "/Users/akyte/mono/sdks/builds/desktop-x86_64/runtime/etc/mono/config" "$@"
