#! /bin/sh
r='/Users/akyte/mono/sdks/builds/desktop-x86_64'
MONO_CFG_DIR='/Users/akyte/mono/sdks/builds/desktop-x86_64/runtime/etc'
export MONO_CFG_DIR
exec "$r/libtool" --mode=execute -dlopen "$r/mono/mini/libmono-2.0.la" "$r/mono/dis/monodis" "$@"
