/* File automatically generated by genmdesc, don't change */

const char mono_amd64_desc [] = {
	"\x0\x0\x0\x0\x0\x0"	/* null entry */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* nop */
	"\x0" "\x0" "\x0" "\x0" "\x1" "\x0" ""	/* hard_nop */
	"\x0" "\x0" "\x0" "\x0" "\x2" "\x0" ""	/* relaxed_nop */
	"\x0" "ii\x0" "\x3" "\x0" ""	/* compare */
	"\x0" "i\x0" "\x0" "\xd" "\x0" ""	/* compare_imm */
	"\x0" "ff\x0" "\xd" "a"	/* fcompare */
	"\x0" "ff\x0" "\xd" "a"	/* rcompare */
	"\x0" "ii\x0" "\x3" "\x0" ""	/* lcompare */
	"\x0" "ii\x0" "\x3" "\x0" ""	/* icompare */
	"\x0" "i\x0" "\x0" "\x8" "\x0" ""	/* icompare_imm */
	"\x0" "i\x0" "\x0" "\xd" "\x0" ""	/* lcompare_imm */
	"ii\x0" "\x0" "\x60" "\x0" ""	/* localloc */
	"i\x0" "\x0" "\x0" "\x60" "\x0" ""	/* localloc_imm */
	"\x0" "b\x0" "\x0" "\x5" "\x0" ""	/* checkthis */
	"\x0" "\x0" "\x0" "\x0" "\x2e" "c"	/* seq_point */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* il_seq_point */
	"\x0" "\x0" "\x0" "\x0" "\x20" "c"	/* voidcall */
	"\x0" "i\x0" "\x0" "\x20" "c"	/* voidcall_reg */
	"\x0" "b\x0" "\x0" "\x20" "c"	/* voidcall_membase */
	"a\x0" "\x0" "\x0" "\x20" "c"	/* call */
	"ai\x0" "\x0" "\x20" "c"	/* call_reg */
	"ab\x0" "\x0" "\x20" "c"	/* call_membase */
	"f\x0" "\x0" "\x0" "\x40" "c"	/* fcall */
	"fi\x0" "\x0" "\x40" "c"	/* fcall_reg */
	"fb\x0" "\x0" "\x40" "c"	/* fcall_membase */
	"f\x0" "\x0" "\x0" "\x40" "c"	/* rcall */
	"fi\x0" "\x0" "\x40" "c"	/* rcall_reg */
	"fb\x0" "\x0" "\x40" "c"	/* rcall_membase */
	"a\x0" "\x0" "\x0" "\x40" "c"	/* lcall */
	"ai\x0" "\x0" "\x40" "c"	/* lcall_reg */
	"ab\x0" "\x0" "\x40" "c"	/* lcall_membase */
	"\x0" "\x0" "\x0" "\x0" "\x40" "c"	/* vcall */
	"\x0" "i\x0" "\x0" "\x40" "c"	/* vcall_reg */
	"\x0" "b\x0" "\x0" "\x40" "c"	/* vcall_membase */
	"\x0" "\x0" "\x0" "\x0" "\x40" "c"	/* vcall2 */
	"\x0" "i\x0" "\x0" "\x40" "c"	/* vcall2_reg */
	"\x0" "b\x0" "\x0" "\x40" "c"	/* vcall2_membase */
	"\x0" "ii\x0" "\xc0" "c"	/* dyn_call */
	"i\x0" "\x0" "\x0" "\xa" "\x0" ""	/* iconst */
	"i\x0" "\x0" "\x0" "\xa" "\x0" ""	/* i8const */
	"f\x0" "\x0" "\x0" "\xe" "\x0" ""	/* r4const */
	"f\x0" "\x0" "\x0" "\x9" "\x0" ""	/* r8const */
	"i\x0" "\x0" "\x0" "\x0" "\x0" ""	/* dummy_iconst */
	"f\x0" "\x0" "\x0" "\x0" "\x0" ""	/* dummy_r8const */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* label */
	"\x0" "i\x0" "\x0" "\x18" "\x0" ""	/* throw */
	"\x0" "i\x0" "\x0" "\x18" "\x0" ""	/* rethrow */
	"\x0" "b\x0" "\x0" "\xb" "\x0" ""	/* oparglist */
	"bi\x0" "\x0" "\x9" "\x0" ""	/* store_membase_reg */
	"bc\x0" "\x0" "\x9" "\x0" ""	/* storei1_membase_reg */
	"bi\x0" "\x0" "\x9" "\x0" ""	/* storei2_membase_reg */
	"bi\x0" "\x0" "\x9" "\x0" ""	/* storei4_membase_reg */
	"bi\x0" "\x0" "\x9" "\x0" ""	/* storei8_membase_reg */
	"bf\x0" "\x0" "\xf" "\x0" ""	/* storer4_membase_reg */
	"bf\x0" "\x0" "\xa" "\x0" ""	/* storer8_membase_reg */
	"bx\x0" "\x0" "\x9" "\x0" ""	/* storex_membase_reg */
	"bx\x0" "\x0" "\x7" "\x0" ""	/* storex_aligned_membase_reg */
	"bx\x0" "\x0" "\x7" "\x0" ""	/* storex_nta_membase_reg */
	"b\x0" "\x0" "\x0" "\xf" "\x0" ""	/* store_membase_imm */
	"b\x0" "\x0" "\x0" "\xb" "\x0" ""	/* storei1_membase_imm */
	"b\x0" "\x0" "\x0" "\xd" "\x0" ""	/* storei2_membase_imm */
	"b\x0" "\x0" "\x0" "\xd" "\x0" ""	/* storei4_membase_imm */
	"b\x0" "\x0" "\x0" "\x12" "\x0" ""	/* storei8_membase_imm */
	"bx\x0" "\x0" "\x9" "\x0" ""	/* storex_membase */
	"ib\x0" "\x0" "\x8" "\x0" ""	/* load_membase */
	"cb\x0" "\x0" "\x9" "\x0" ""	/* loadi1_membase */
	"cb\x0" "\x0" "\x9" "\x0" ""	/* loadu1_membase */
	"ib\x0" "\x0" "\x9" "\x0" ""	/* loadi2_membase */
	"ib\x0" "\x0" "\x9" "\x0" ""	/* loadu2_membase */
	"ib\x0" "\x0" "\x9" "\x0" ""	/* loadi4_membase */
	"ib\x0" "\x0" "\x9" "\x0" ""	/* loadu4_membase */
	"ib\x0" "\x0" "\x12" "\x0" ""	/* loadi8_membase */
	"fb\x0" "\x0" "\x10" "\x0" ""	/* loadr4_membase */
	"fb\x0" "\x0" "\x10" "\x0" ""	/* loadr8_membase */
	"xb\x0" "\x0" "\x9" "\x0" ""	/* loadx_membase */
	"xb\x0" "\x0" "\x7" "\x0" ""	/* loadx_aligned_membase */
	"i\x0" "\x0" "\x0" "\x10" "\x0" ""	/* load_mem */
	"i\x0" "\x0" "\x0" "\x10" "\x0" ""	/* loadu1_mem */
	"i\x0" "\x0" "\x0" "\x10" "\x0" ""	/* loadu2_mem */
	"i\x0" "\x0" "\x0" "\x10" "\x0" ""	/* loadi4_mem */
	"i\x0" "\x0" "\x0" "\xa" "\x0" ""	/* loadu4_mem */
	"i\x0" "\x0" "\x0" "\x10" "\x0" ""	/* loadi8_mem */
	"ii\x0" "\x0" "\x3" "\x0" ""	/* move */
	"ff\x0" "\x0" "\x8" "\x0" ""	/* fmove */
	"ff\x0" "\x0" "\x8" "\x0" ""	/* rmove */
	"if\x0" "\x0" "\x10" "\x0" ""	/* move_f_to_i4 */
	"fi\x0" "\x0" "\x10" "\x0" ""	/* move_i4_to_f */
	"if\x0" "\x0" "\x5" "\x0" ""	/* move_f_to_i8 */
	"fi\x0" "\x0" "\x5" "\x0" ""	/* move_i8_to_f */
	"ii\x0" "\x0" "\x8" "1"	/* add_imm */
	"ii\x0" "\x0" "\x8" "1"	/* sub_imm */
	"ii\x0" "\x0" "\xc" "\x0" ""	/* mul_imm */
	"ii\x0" "\x0" "\x8" "1"	/* and_imm */
	"ii\x0" "\x0" "\x8" "1"	/* or_imm */
	"ii\x0" "\x0" "\x8" "1"	/* xor_imm */
	"ii\x0" "\x0" "\x8" "1"	/* shl_imm */
	"ii\x0" "\x0" "\x8" "1"	/* shr_imm */
	"ii\x0" "\x0" "\x8" "1"	/* shr_un_imm */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* br */
	"\x0" "\x0" "\x0" "\x0" "xc"	/* tailcall */
	"\x0" "\x0" "\x0" "\x0" "\x2" "\x0" ""	/* break */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* ceq */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cgt */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cgt.un */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* clt */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* clt.un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_eq */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ge */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_gt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_le */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_lt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ne_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ge_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_gt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_le_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_lt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ov */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_no */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_c */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_nc */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ieq */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ige */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_igt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ile */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ilt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ine_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ige_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_igt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ile_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ilt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_iov */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ino */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ic */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_inc */
	"iii\x0" "\x3" "1"	/* long_add */
	"iii\x0" "\x3" "1"	/* long_sub */
	"iii\x0" "\x4" "1"	/* long_mul */
	"aai\x0" "\x10" "d"	/* long_div */
	"aai\x0" "\x10" "d"	/* long_div_un */
	"dai\x0" "\x10" "a"	/* long_rem */
	"dai\x0" "\x10" "a"	/* long_rem_un */
	"iii\x0" "\x3" "1"	/* long_and */
	"iii\x0" "\x3" "1"	/* long_or */
	"iii\x0" "\x3" "1"	/* long_xor */
	"iis\x0" "\x3" "1"	/* long_shl */
	"iis\x0" "\x3" "1"	/* long_shr */
	"iis\x0" "\x3" "1"	/* long_shr_un */
	"ii\x0" "\x0" "\x3" "1"	/* long_neg */
	"ii\x0" "\x0" "\x3" "1"	/* long_not */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_conv_to_i1 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_conv_to_i2 */
	"ii\x0" "\x0" "\x3" "\x0" ""	/* long_conv_to_i4 */
	"ii\x0" "\x0" "\x3" "\x0" ""	/* long_conv_to_i8 */
	"fi\x0" "\x0" "\xf" "\x0" ""	/* long_conv_to_r4 */
	"fi\x0" "\x0" "\x9" "\x0" ""	/* long_conv_to_r8 */
	"ii\x0" "\x0" "\x3" "\x0" ""	/* long_conv_to_u4 */
	"ii\x0" "\x0" "\x3" "\x0" ""	/* long_conv_to_u8 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_conv_to_u2 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_conv_to_u1 */
	"iii\x0" "\x10" "1"	/* long_mul_ovf */
	"iii\x0" "\x16" "\x0" ""	/* long_mul_ovf_un */
	"ii\x0" "\x0" "\x10" "\x0" ""	/* long_conv_to_ovf_i4_un */
	"ii\x0" "\x0" "\xf" "\x0" ""	/* long_conv_to_ovf_u4 */
	"c\x0" "\x0" "\x0" "\x40" "\x0" ""	/* long_ceq */
	"c\x0" "\x0" "\x0" "\x40" "\x0" ""	/* long_cgt */
	"c\x0" "\x0" "\x0" "\x40" "\x0" ""	/* long_cgt_un */
	"c\x0" "\x0" "\x0" "\x40" "\x0" ""	/* long_clt */
	"c\x0" "\x0" "\x0" "\x40" "\x0" ""	/* long_clt_un */
	"fi\x0" "\x0" "\x40" "\x0" ""	/* long_conv_to_r_un */
	"ii\x0" "\x0" "\xc" "1"	/* long_add_imm */
	"ii\x0" "\x0" "\xc" "1"	/* long_sub_imm */
	"ii\x0" "\x0" "\xc" "1"	/* long_mul_imm */
	"ii\x0" "\x0" "\xc" "1"	/* long_and_imm */
	"ii\x0" "\x0" "\xc" "1"	/* long_or_imm */
	"ii\x0" "\x0" "\xc" "1"	/* long_xor_imm */
	"ii\x0" "\x0" "\xb" "1"	/* long_shl_imm */
	"ii\x0" "\x0" "\xb" "1"	/* long_shr_imm */
	"ii\x0" "\x0" "\xb" "1"	/* long_shr_un_imm */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_beq */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_bge */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_bgt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_ble */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_blt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_bne_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_bge_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_bgt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_ble_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_blt_un */
	"iii\x0" "\x4" "1"	/* int_add */
	"iii\x0" "\x4" "1"	/* int_sub */
	"iii\x0" "\x4" "1"	/* int_mul */
	"aai\x0" "\x20" "d"	/* int_div */
	"aai\x0" "\x20" "d"	/* int_div_un */
	"dai\x0" "\x20" "a"	/* int_rem */
	"dai\x0" "\x20" "a"	/* int_rem_un */
	"iii\x0" "\x4" "1"	/* int_and */
	"iii\x0" "\x4" "1"	/* int_or */
	"iii\x0" "\x4" "1"	/* int_xor */
	"iis\x0" "\x4" "1"	/* int_shl */
	"iis\x0" "\x4" "1"	/* int_shr */
	"iis\x0" "\x4" "1"	/* int_shr_un */
	"ii\x0" "\x0" "\x4" "1"	/* int_neg */
	"ii\x0" "\x0" "\x4" "1"	/* int_not */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* int_conv_to_i1 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* int_conv_to_i2 */
	"ii\x0" "\x0" "\x3" "\x0" ""	/* int_conv_to_i4 */
	"ii\x0" "\x0" "\x3" "\x0" ""	/* int_conv_to_i8 */
	"fi\x0" "\x0" "\xf" "\x0" ""	/* int_conv_to_r4 */
	"fi\x0" "\x0" "\x9" "\x0" ""	/* int_conv_to_r8 */
	"ii\x0" "\x0" "\x3" "\x0" ""	/* int_conv_to_u4 */
	"ii\x0" "\x0" "\x3" "\x0" ""	/* int_conv_to_u8 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* int_conv_to_u */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* int_conv_to_u2 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* int_conv_to_u1 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* int_conv_to_i */
	"iii\x0" "\x20" "1"	/* int_mul_ovf */
	"iii\x0" "\x20" "1"	/* int_mul_ovf_un */
	"iii\x0" "\x4" "1"	/* int_adc */
	"ii\x0" "\x0" "\x8" "1"	/* int_adc_imm */
	"iii\x0" "\x4" "1"	/* int_sbb */
	"ii\x0" "\x0" "\x8" "1"	/* int_sbb_imm */
	"iii\x0" "\x10" "1"	/* int_addcc */
	"iii\x0" "\x10" "1"	/* int_subcc */
	"ii\x0" "\x0" "\x8" "1"	/* int_add_imm */
	"ii\x0" "\x0" "\x8" "1"	/* int_sub_imm */
	"ii\x0" "\x0" "\x20" "1"	/* int_mul_imm */
	"ai\x0" "\x0" "\x20" "d"	/* int_div_imm */
	"ai\x0" "\x0" "\x20" "d"	/* int_div_un_imm */
	"di\x0" "\x0" "\x20" "a"	/* int_rem_un_imm */
	"ii\x0" "\x0" "\x8" "1"	/* int_and_imm */
	"ii\x0" "\x0" "\x8" "1"	/* int_or_imm */
	"ii\x0" "\x0" "\x8" "1"	/* int_xor_imm */
	"ii\x0" "\x0" "\x8" "1"	/* int_shl_imm */
	"ii\x0" "\x0" "\x8" "1"	/* int_shr_imm */
	"ii\x0" "\x0" "\x8" "1"	/* int_shr_un_imm */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_ceq */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_cgt */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_cgt_un */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_clt */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_clt_un */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_cneq */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_cge */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_cle */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_cge_un */
	"c\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_cle_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_beq */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bge */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bgt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_ble */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_blt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bne_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bge_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bgt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_ble_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_blt_un */
	"\x0" "\x0" "\x0" "\x0" "\xd" "\x0" ""	/* float_beq */
	"\x0" "\x0" "\x0" "\x0" "\x20" "\x0" ""	/* float_bge */
	"\x0" "\x0" "\x0" "\x0" "\xd" "\x0" ""	/* float_bgt */
	"\x0" "\x0" "\x0" "\x0" "\x20" "\x0" ""	/* float_ble */
	"\x0" "\x0" "\x0" "\x0" "\xd" "\x0" ""	/* float_blt */
	"\x0" "\x0" "\x0" "\x0" "\x12" "\x0" ""	/* float_bne_un */
	"\x0" "\x0" "\x0" "\x0" "\xd" "\x0" ""	/* float_bge_un */
	"\x0" "\x0" "\x0" "\x0" "\x1e" "\x0" ""	/* float_bgt_un */
	"\x0" "\x0" "\x0" "\x0" "\xd" "\x0" ""	/* float_ble_un */
	"\x0" "\x0" "\x0" "\x0" "\x1e" "\x0" ""	/* float_blt_un */
	"fff\x0" "\x5" "1"	/* float_add */
	"fff\x0" "\x5" "1"	/* float_sub */
	"fff\x0" "\x5" "1"	/* float_mul */
	"fff\x0" "\x5" "1"	/* float_div */
	"fff\x0" "\x5" "1"	/* float_div_un */
	"fff\x0" "\x13" "1"	/* float_rem */
	"fff\x0" "\x13" "1"	/* float_rem_un */
	"fff\x0" "\x5" "1"	/* r4_add */
	"fff\x0" "\x5" "1"	/* r4_sub */
	"fff\x0" "\x5" "1"	/* r4_mul */
	"fff\x0" "\x5" "1"	/* r4_div */
	"ff\x0" "\x0" "\x17" "1"	/* float_neg */
	"ff\x0" "\x0" "\x3" "1"	/* float_not */
	"if\x0" "\x0" "1\x0" ""	/* float_conv_to_i1 */
	"if\x0" "\x0" "1\x0" ""	/* float_conv_to_i2 */
	"if\x0" "\x0" "1\x0" ""	/* float_conv_to_i4 */
	"if\x0" "\x0" "1\x0" ""	/* float_conv_to_i8 */
	"ff\x0" "\x0" "\x11" "\x0" ""	/* float_conv_to_r4 */
	"if\x0" "\x0" "1\x0" ""	/* float_conv_to_u4 */
	"if\x0" "\x0" "1\x0" ""	/* float_conv_to_u8 */
	"ff\x0" "\x0" "\x17" "1"	/* r4_neg */
	"if\x0" "\x0" "\x20" "\x0" ""	/* r4_conv_to_i1 */
	"if\x0" "\x0" "\x20" "\x0" ""	/* r4_conv_to_i2 */
	"if\x0" "\x0" "\x10" "\x0" ""	/* r4_conv_to_i4 */
	"if\x0" "\x0" "\x20" "\x0" ""	/* r4_conv_to_i8 */
	"ff\x0" "\x0" "\x11" "\x0" ""	/* r4_conv_to_r4 */
	"ff\x0" "\x0" "\x11" "\x0" ""	/* r4_conv_to_r8 */
	"if\x0" "\x0" "\x20" "\x0" ""	/* r4_conv_to_u4 */
	"if\x0" "\x0" "1\x0" ""	/* float_conv_to_u2 */
	"if\x0" "\x0" "1\x0" ""	/* float_conv_to_u1 */
	"if\x0" "\x0" "1\x0" ""	/* float_conv_to_i */
	"af\x0" "\x0" "\x28" "\x0" ""	/* float_conv_to_ovf_i */
	"af\x0" "\x0" "\x28" "\x0" ""	/* float_conv_to_ovd_u */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* float_mul_ovf */
	"iff\x0" "\x23" "\x0" ""	/* float_ceq */
	"iff\x0" "\x23" "\x0" ""	/* float_cgt */
	"iff\x0" "0\x0" ""	/* float_cgt_un */
	"iff\x0" "\x23" "\x0" ""	/* float_clt */
	"iff\x0" "\x2a" "\x0" ""	/* float_clt_un */
	"iff\x0" "\x2a" "\x0" ""	/* float_cneq */
	"iff\x0" "\x23" "\x0" ""	/* float_cge */
	"iff\x0" "\x23" "\x0" ""	/* float_cle */
	"ifb\x0" "\x23" "\x0" ""	/* float_ceq_membase */
	"ifb\x0" "\x23" "\x0" ""	/* float_cgt_membase */
	"ifb\x0" "0\x0" ""	/* float_cgt_un_membase */
	"ifb\x0" "\x23" "\x0" ""	/* float_clt_membase */
	"ifb\x0" "\x2a" "\x0" ""	/* float_clt_un_membase */
	"if\x0" "\x0" "\x2e" "\x0" ""	/* float_conv_to_u */
	"ff\x0" "\x0" "\x2b" "\x0" ""	/* ckfinite */
	"if\x0" "\x0" "\x20" "\x0" ""	/* r4_conv_to_u2 */
	"if\x0" "\x0" "\x20" "\x0" ""	/* r4_conv_to_u1 */
	"iff\x0" "\x23" "\x0" ""	/* r4_ceq */
	"iff\x0" "\x23" "\x0" ""	/* r4_cgt */
	"iff\x0" "0\x0" ""	/* r4_cgt_un */
	"iff\x0" "\x23" "\x0" ""	/* r4_clt */
	"iff\x0" "\x2a" "\x0" ""	/* r4_clt_un */
	"iff\x0" "\x2a" "\x0" ""	/* r4_cneq */
	"iff\x0" "\x23" "\x0" ""	/* r4_cge */
	"iff\x0" "\x23" "\x0" ""	/* r4_cle */
	"i\x0" "\x0" "\x0" "\x12" "\x0" ""	/* jump_table */
	"i\x0" "\x0" "\x0" "\xa" "\x0" ""	/* aot_const */
	"\x0" "\x0" "\x0" "\x0" "\xe" "c"	/* call_handler */
	"\x0" "\x0" "\x0" "\x0" "\x10" "\x0" ""	/* start_handler */
	"\x0" "a\x0" "\x0" "\x9" "\x0" ""	/* endfilter */
	"\x0" "\x0" "\x0" "\x0" "\x9" "\x0" ""	/* endfinally */
	"a\x0" "\x0" "\x0" "\x10" "\x0" ""	/* get_ex_obj */
	"iii\x0" "\x10" "1"	/* int_min_un */
	"iii\x0" "\x10" "1"	/* int_max_un */
	"iii\x0" "\x10" "1"	/* long_min_un */
	"iii\x0" "\x10" "1"	/* long_max_un */
	"iii\x0" "\x10" "1"	/* int_min */
	"iii\x0" "\x10" "1"	/* int_max */
	"iii\x0" "\x10" "1"	/* long_min */
	"iii\x0" "\x10" "1"	/* long_max */
	"iii\x0" "\x3" "1"	/* adc */
	"ii\x0" "\x0" "\x8" "1"	/* adc_imm */
	"iii\x0" "\x3" "1"	/* sbb */
	"ii\x0" "\x0" "\x8" "1"	/* sbb_imm */
	"iii\x0" "\x3" "1"	/* addcc */
	"iii\x0" "\x3" "1"	/* subcc */
	"\x0" "i\x0" "\x0" "\x3" "\x0" ""	/* br_reg */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* sext_i1 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* sext_i2 */
	"ii\x0" "\x0" "\x8" "\x0" ""	/* sext_i4 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* zext_i4 */
	"iii\x0" "\x3" "1"	/* laddcc */
	"iii\x0" "\x3" "1"	/* lsubcc */
	"ff\x0" "\x0" "\x20" "\x0" ""	/* sin */
	"ff\x0" "\x0" "\x20" "\x0" ""	/* cos */
	"ff\x0" "\x0" "\x20" "1"	/* abs */
	"ff\x0" "\x0" "\x3b" "\x0" ""	/* tan */
	"ff\x0" "\x0" "\x9" "\x0" ""	/* atan */
	"ff\x0" "\x0" "\x20" "\x0" ""	/* sqrt */
	"\x0" "ai\x0" "8d"	/* card_table_wbarrier */
	"i\x0" "\x0" "\x0" "\x20" "\x0" ""	/* tls_get */
	"\x0" "i\x0" "\x0" "\x10" "\x0" ""	/* tls_set */
	"\x0" "i\x0" "\x0" "\x0" "\x0" ""	/* dummy_use */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* dummy_store */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* not_reached */
	"\x0" "i\x0" "\x0" "\x0" "\x0" ""	/* not_null */
	"xxx\x0" "\x4" "1"	/* addps */
	"xxx\x0" "\x4" "1"	/* divps */
	"xxx\x0" "\x4" "1"	/* mulps */
	"xxx\x0" "\x4" "1"	/* subps */
	"xxx\x0" "\x4" "1"	/* maxps */
	"xxx\x0" "\x4" "1"	/* minps */
	"xxx\x0" "\x5" "1"	/* compps */
	"xxx\x0" "\x4" "1"	/* andps */
	"xxx\x0" "\x4" "1"	/* andnps */
	"xxx\x0" "\x4" "1"	/* orps */
	"xxx\x0" "\x4" "1"	/* xorps */
	"xxx\x0" "\x5" "1"	/* haddps */
	"xxx\x0" "\x5" "1"	/* hsubps */
	"xxx\x0" "\x5" "1"	/* addsubps */
	"xx\x0" "\x0" "\x5" "\x0" ""	/* dupps_low */
	"xx\x0" "\x0" "\x5" "\x0" ""	/* dupps_high */
	"xx\x0" "\x0" "\x5" "\x0" ""	/* rsqrtps */
	"xx\x0" "\x0" "\x5" "\x0" ""	/* sqrtps */
	"xx\x0" "\x0" "\x5" "\x0" ""	/* rcpps */
	"xx\x0" "\x0" "\x6" "\x0" ""	/* pshufflew_high */
	"xx\x0" "\x0" "\x6" "\x0" ""	/* pshufflew_low */
	"xx\x0" "\x0" "\x6" "\x0" ""	/* pshuffled */
	"xxx\x0" "\x5" "1"	/* shufps */
	"xxx\x0" "\x6" "1"	/* shufpd */
	"xxx\x0" "\x5" "1"	/* addpd */
	"xxx\x0" "\x5" "1"	/* divpd */
	"xxx\x0" "\x5" "1"	/* mulpd */
	"xxx\x0" "\x5" "1"	/* subpd */
	"xxx\x0" "\x5" "1"	/* maxpd */
	"xxx\x0" "\x5" "1"	/* minpd */
	"xxx\x0" "\x6" "1"	/* comppd */
	"xxx\x0" "\x5" "1"	/* andpd */
	"xxx\x0" "\x5" "1"	/* andnpd */
	"xxx\x0" "\x5" "1"	/* orpd */
	"xxx\x0" "\x5" "1"	/* xorpd */
	"xxx\x0" "\x6" "1"	/* haddpd */
	"xxx\x0" "\x6" "1"	/* hsubpd */
	"xxx\x0" "\x6" "1"	/* addsubpd */
	"xx\x0" "\x0" "\x6" "\x0" ""	/* duppd */
	"xx\x0" "\x0" "\x5" "1"	/* sqrtpd */
	"ix\x0" "\x0" "\x6" "\x0" ""	/* extract_mask */
	"xxx\x0" "\x5" "1"	/* pand */
	"xxx\x0" "\x5" "1"	/* por */
	"xxx\x0" "\x5" "1"	/* pxor */
	"xxx\x0" "\x5" "1"	/* paddb */
	"xxx\x0" "\x5" "1"	/* paddw */
	"xxx\x0" "\x5" "1"	/* paddd */
	"xxx\x0" "\x5" "1"	/* paddq */
	"xxx\x0" "\x5" "1"	/* psubb */
	"xxx\x0" "\x5" "1"	/* psubw */
	"xxx\x0" "\x5" "1"	/* psubd */
	"xxx\x0" "\x5" "1"	/* psubq */
	"xxx\x0" "\x5" "1"	/* pmaxb_un */
	"xxx\x0" "\x6" "1"	/* pmaxw_un */
	"xxx\x0" "\x6" "1"	/* pmaxd_un */
	"xxx\x0" "\x6" "1"	/* pmaxb */
	"xxx\x0" "\x5" "1"	/* pmaxw */
	"xxx\x0" "\x6" "1"	/* pmaxd */
	"xxx\x0" "\x5" "1"	/* pavgb_un */
	"xxx\x0" "\x5" "1"	/* pavgw_un */
	"xxx\x0" "\x5" "1"	/* pminb_un */
	"xxx\x0" "\x6" "1"	/* pminw_un */
	"xxx\x0" "\x6" "1"	/* pmind_un */
	"xxx\x0" "\x6" "1"	/* pminb */
	"xxx\x0" "\x5" "1"	/* pminw */
	"xxx\x0" "\x6" "1"	/* pmind */
	"xxx\x0" "\x5" "1"	/* pcmpeqb */
	"xxx\x0" "\x5" "1"	/* pcmpeqw */
	"xxx\x0" "\x5" "1"	/* pcmpeqd */
	"xxx\x0" "\x6" "1"	/* pcmpeqq */
	"xxx\x0" "\x5" "1"	/* pcmpgtb */
	"xxx\x0" "\x5" "1"	/* pcmpgtw */
	"xxx\x0" "\x5" "1"	/* pcmpgtd */
	"xxx\x0" "\x6" "1"	/* pcmpgtq */
	"xxx\x0" "\x5" "1"	/* psumabsdiff */
	"xxx\x0" "\x5" "1"	/* unpack_lowb */
	"xxx\x0" "\x5" "1"	/* unpack_loww */
	"xxx\x0" "\x5" "1"	/* unpack_lowd */
	"xxx\x0" "\x5" "1"	/* unpack_lowq */
	"xxx\x0" "\x5" "1"	/* unpack_lowps */
	"xxx\x0" "\x5" "1"	/* unpack_lowpd */
	"xxx\x0" "\x5" "1"	/* unpack_highb */
	"xxx\x0" "\x5" "1"	/* unpack_highw */
	"xxx\x0" "\x5" "1"	/* unpack_highd */
	"xxx\x0" "\x5" "1"	/* unpack_highq */
	"xxx\x0" "\x5" "1"	/* unpack_highps */
	"xxx\x0" "\x5" "1"	/* unpack_highpd */
	"xxx\x0" "\x5" "1"	/* packw */
	"xxx\x0" "\x5" "1"	/* packd */
	"xxx\x0" "\x5" "1"	/* packw_un */
	"xxx\x0" "\x6" "1"	/* packd_un */
	"xxx\x0" "\x5" "1"	/* paddb_sat */
	"xxx\x0" "\x5" "1"	/* paddb_sat_un */
	"xxx\x0" "\x5" "1"	/* paddw_sat */
	"xxx\x0" "\x5" "1"	/* paddw_sat_un */
	"xxx\x0" "\x5" "1"	/* psubb_sat */
	"xxx\x0" "\x5" "1"	/* psubb_sat_un */
	"xxx\x0" "\x5" "1"	/* psubw_sat */
	"xxx\x0" "\x5" "1"	/* psubw_sat_un */
	"xxx\x0" "\x5" "1"	/* pmulw */
	"xxx\x0" "\x6" "1"	/* pmuld */
	"xxx\x0" "\x5" "1"	/* pmulq */
	"xxx\x0" "\x5" "1"	/* pmul_high_un */
	"xxx\x0" "\x5" "1"	/* pmul_high */
	"xx\x0" "\x0" "\x6" "1"	/* pshrw */
	"xxx\x0" "\x5" "1"	/* pshrw_reg */
	"xx\x0" "\x0" "\x6" "1"	/* psarw */
	"xxx\x0" "\x5" "1"	/* psarw_reg */
	"xx\x0" "\x0" "\x6" "1"	/* pshlw */
	"xxx\x0" "\x5" "1"	/* pshlw_reg */
	"xx\x0" "\x0" "\x6" "1"	/* pshrd */
	"xxx\x0" "\x5" "1"	/* pshrd_reg */
	"xx\x0" "\x0" "\x6" "1"	/* pshrq */
	"xxx\x0" "\x5" "1"	/* pshrq_reg */
	"xx\x0" "\x0" "\x6" "1"	/* psard */
	"xxx\x0" "\x5" "1"	/* psard_reg */
	"xx\x0" "\x0" "\x6" "1"	/* pshld */
	"xxx\x0" "\x5" "1"	/* pshld_reg */
	"xx\x0" "\x0" "\x6" "1"	/* pshlq */
	"xxx\x0" "\x5" "1"	/* pshlq_reg */
	"ix\x0" "\x0" "\x5" "\x0" ""	/* extract_i4 */
	"fi\x0" "\x0" "\xa" "\x0" ""	/* iconv_to_r4_raw */
	"ix\x0" "\x0" "\xd" "\x0" ""	/* extract_i2 */
	"ix\x0" "\x0" "\xd" "\x0" ""	/* extract_u2 */
	"ix\x0" "\x0" "\xd" "\x0" ""	/* extract_i1 */
	"ix\x0" "\x0" "\xd" "\x0" ""	/* extract_u1 */
	"fx\x0" "\x0" "\x5" "\x0" ""	/* extract_r8 */
	"ix\x0" "\x0" "\x9" "\x0" ""	/* extract_i8 */
	"xxi\x0" "\x6" "1"	/* insert_i2 */
	"ix\x0" "\x0" "\x6" "\x0" ""	/* extractx_u2 */
	"xii\x0" "\x12" "x"	/* insertx_u1_slow */
	"xxi\x0" "\x10" "x"	/* insertx_i4_slow */
	"xxf\x0" "\x18" "\x0" ""	/* insertx_r4_slow */
	"xxf\x0" "\x18" "\x0" ""	/* insertx_r8_slow */
	"xxi\x0" "\xd" "\x0" ""	/* insertx_i8_slow */
	"xf\x0" "\x0" "\x4" "\x0" ""	/* fconv_to_r8_x */
	"yx\x0" "\x0" "\x7" "\x0" ""	/* xconv_r8_to_i4 */
	"xi\x0" "\x0" "\x5" "\x0" ""	/* iconv_to_x */
	"xi\x0" "\x0" "\x12" "\x0" ""	/* expand_i2 */
	"xi\x0" "\x0" "\xb" "\x0" ""	/* expand_i4 */
	"xf\x0" "\x0" "\x10" "\x0" ""	/* expand_r4 */
	"xi\x0" "\x0" "\xb" "\x0" ""	/* expand_i8 */
	"xf\x0" "\x0" "\xd" "\x0" ""	/* expand_r8 */
	"\x0" "b\x0" "\x0" "\x4" "\x0" ""	/* prefetch_membase */
	"xx\x0" "\x0" "\x5" "1"	/* cvtdq2pd */
	"xx\x0" "\x0" "\x4" "1"	/* cvtdq2ps */
	"xx\x0" "\x0" "\x5" "1"	/* cvtpd2dq */
	"xx\x0" "\x0" "\x5" "1"	/* cvtpd2ps */
	"xx\x0" "\x0" "\x5" "1"	/* cvtps2dq */
	"xx\x0" "\x0" "\x4" "1"	/* cvtps2pd */
	"xx\x0" "\x0" "\x5" "1"	/* cvttpd2dq */
	"xx\x0" "\x0" "\x5" "1"	/* cvttps2dq */
	"xx\x0" "\x0" "\x5" "\x0" ""	/* xmove */
	"x\x0" "\x0" "\x0" "\x5" "\x0" ""	/* xzero */
	"x\x0" "\x0" "\x0" "\x5" "\x0" ""	/* xones */
	"\x0" "\x0" "\x0" "\x0" "\x3" "\x0" ""	/* memory_barrier */
	"cb\x0" "\x0" "\x9" "\x0" ""	/* atomic_load_i1 */
	"ib\x0" "\x0" "\x9" "\x0" ""	/* atomic_load_i2 */
	"ib\x0" "\x0" "\x9" "\x0" ""	/* atomic_load_i4 */
	"ib\x0" "\x0" "\x9" "\x0" ""	/* atomic_load_i8 */
	"cb\x0" "\x0" "\x9" "\x0" ""	/* atomic_load_u1 */
	"ib\x0" "\x0" "\x9" "\x0" ""	/* atomic_load_u2 */
	"ib\x0" "\x0" "\x9" "\x0" ""	/* atomic_load_u4 */
	"ib\x0" "\x0" "\x9" "\x0" ""	/* atomic_load_u8 */
	"fb\x0" "\x0" "\x10" "\x0" ""	/* atomic_load_r4 */
	"fb\x0" "\x0" "\x10" "\x0" ""	/* atomic_load_r8 */
	"bc\x0" "\x0" "\xc" "\x0" ""	/* atomic_store_i1 */
	"bi\x0" "\x0" "\xc" "\x0" ""	/* atomic_store_i2 */
	"bi\x0" "\x0" "\xc" "\x0" ""	/* atomic_store_i4 */
	"bi\x0" "\x0" "\xc" "\x0" ""	/* atomic_store_i8 */
	"bc\x0" "\x0" "\xc" "\x0" ""	/* atomic_store_u1 */
	"bi\x0" "\x0" "\xc" "\x0" ""	/* atomic_store_u2 */
	"bi\x0" "\x0" "\xc" "\x0" ""	/* atomic_store_u4 */
	"bi\x0" "\x0" "\xc" "\x0" ""	/* atomic_store_u8 */
	"bf\x0" "\x0" "\x12" "\x0" ""	/* atomic_store_r4 */
	"bf\x0" "\x0" "\xd" "\x0" ""	/* atomic_store_r8 */
	"ibi\x0" "\x20" "\x0" ""	/* atomic_add_i4 */
	"ibi\x0" "\x20" "\x0" ""	/* atomic_add_i8 */
	"ibi\x0" "\xc" "\x0" ""	/* atomic_exchange_i4 */
	"ibi\x0" "\xc" "\x0" ""	/* atomic_exchange_i8 */
	"abia\x18" "\x0" ""	/* atomic_cas_i4 */
	"abia\x18" "\x0" ""	/* atomic_cas_i8 */
	"iii\x0" "\x10" "1"	/* cmov_ieq */
	"iii\x0" "\x10" "1"	/* cmov_ige */
	"iii\x0" "\x10" "1"	/* cmov_igt */
	"iii\x0" "\x10" "1"	/* cmov_ile */
	"iii\x0" "\x10" "1"	/* cmov_ilt */
	"iii\x0" "\x10" "1"	/* cmov_ine_un */
	"iii\x0" "\x10" "1"	/* cmov_ige_un */
	"iii\x0" "\x10" "1"	/* cmov_igt_un */
	"iii\x0" "\x10" "1"	/* cmov_ile_un */
	"iii\x0" "\x10" "1"	/* cmov_ilt_un */
	"iii\x0" "\x10" "1"	/* cmov_leq */
	"iii\x0" "\x10" "1"	/* cmov_lge */
	"iii\x0" "\x10" "1"	/* cmov_lgt */
	"iii\x0" "\x10" "1"	/* cmov_lle */
	"iii\x0" "\x10" "1"	/* cmov_llt */
	"iii\x0" "\x10" "1"	/* cmov_lne_un */
	"iii\x0" "\x10" "1"	/* cmov_lge_un */
	"iii\x0" "\x10" "1"	/* cmov_lgt_un */
	"iii\x0" "\x10" "1"	/* cmov_lle_un */
	"iii\x0" "\x10" "1"	/* cmov_llt_un */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* liverange_start */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* liverange_end */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* gc_liveness_def */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* gc_liveness_use */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* gc_spill_slot_liveness_def */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* gc_param_slot_liveness_def */
	"\x0" "i\x0" "\x0" "\x28" "c"	/* gc_safe_point */
	"\x0" "A\x0" "\x0" "\x20" "c"	/* generic_class_init */
	"\x0" "i\x0" "\x0" "\x5" "\x0" ""	/* x86_test_null */
	"\x0" "bi\x0" "\x9" "\x0" ""	/* x86_compare_membase_reg */
	"\x0" "b\x0" "\x0" "\xd" "\x0" ""	/* x86_compare_membase_imm */
	"\x0" "b\x0" "\x0" "\x9" "\x0" ""	/* x86_compare_membase8_imm */
	"\x0" "ib\x0" "\x8" "\x0" ""	/* x86_compare_reg_membase */
	"ii\x0" "\x0" "\x3" "1"	/* x86_inc_reg */
	"\x0" "b\x0" "\x0" "\x8" "\x0" ""	/* x86_inc_membase */
	"ii\x0" "\x0" "\x3" "1"	/* x86_dec_reg */
	"\x0" "b\x0" "\x0" "\x8" "\x0" ""	/* x86_dec_membase */
	"\x0" "b\x0" "\x0" "\xd" "\x0" ""	/* x86_add_membase_imm */
	"\x0" "b\x0" "\x0" "\xd" "\x0" ""	/* x86_sub_membase_imm */
	"\x0" "b\x0" "\x0" "\xc" "\x0" ""	/* x86_and_membase_imm */
	"\x0" "b\x0" "\x0" "\xc" "\x0" ""	/* x86_or_membase_imm */
	"\x0" "b\x0" "\x0" "\xc" "\x0" ""	/* x86_xor_membase_imm */
	"\x0" "bi\x0" "\xc" "\x0" ""	/* x86_add_membase_reg */
	"\x0" "bi\x0" "\xc" "\x0" ""	/* x86_sub_membase_reg */
	"\x0" "bi\x0" "\xc" "\x0" ""	/* x86_and_membase_reg */
	"\x0" "bi\x0" "\xc" "\x0" ""	/* x86_or_membase_reg */
	"\x0" "bi\x0" "\xc" "\x0" ""	/* x86_xor_membase_reg */
	"\x0" "bi\x0" "\xe" "\x0" ""	/* x86_mul_membase_reg */
	"iib\x0" "\xd" "1"	/* x86_add_reg_membase */
	"iib\x0" "\xd" "1"	/* x86_sub_reg_membase */
	"iib\x0" "\xd" "1"	/* x86_mul_reg_membase */
	"iib\x0" "\xd" "1"	/* x86_and_reg_membase */
	"iib\x0" "\xd" "1"	/* x86_or_reg_membase */
	"iib\x0" "\xd" "1"	/* x86_xor_reg_membase */
	"\x0" "b\x0" "\x0" "\x8" "\x0" ""	/* x86_push_membase */
	"\x0" "\x0" "\x0" "\x0" "\x6" "\x0" ""	/* x86_push_imm */
	"\x0" "i\x0" "\x0" "\x3" "\x0" ""	/* x86_push */
	"\x0" "b\x0" "\x0" "\x28" "\x0" ""	/* x86_push_obj */
	"iii\x0" "\x8" "\x0" ""	/* x86_lea */
	"ii\x0" "\x0" "\xb" "\x0" ""	/* x86_lea_membase */
	"\x0" "ii\x0" "\x2" "x"	/* x86_xchg */
	"\x0" "f\x0" "\x0" "\x3" "\x0" ""	/* x86_fpop */
	"\x0" "b\x0" "\x0" "\x9" "\x0" ""	/* x86_seteq_membase */
	"\x0" "i\x0" "\x0" "\x5" "\x0" ""	/* amd64_test_null */
	"ff\x0" "\x0" "\xe" "m"	/* amd64_set_xmmreg_r4 */
	"ff\x0" "\x0" "\xe" "m"	/* amd64_set_xmmreg_r8 */
	"\x0" "bi\x0" "\x8" "\x0" ""	/* amd64_icompare_membase_reg */
	"\x0" "b\x0" "\x0" "\xd" "\x0" ""	/* amd64_icompare_membase_imm */
	"\x0" "ib\x0" "\x8" "\x0" ""	/* amd64_icompare_reg_membase */
	"\x0" "bi\x0" "\x9" "\x0" ""	/* amd64_compare_membase_reg */
	"\x0" "b\x0" "\x0" "\xe" "\x0" ""	/* amd64_compare_membase_imm */
	"\x0" "ib\x0" "\x9" "\x0" ""	/* amd64_compare_reg_membase */
	"\x0" "bi\x0" "\xd" "\x0" ""	/* amd64_add_membase_reg */
	"\x0" "bi\x0" "\xd" "\x0" ""	/* amd64_sub_membase_reg */
	"\x0" "bi\x0" "\xd" "\x0" ""	/* amd64_and_membase_reg */
	"\x0" "bi\x0" "\xd" "\x0" ""	/* amd64_or_membase_reg */
	"\x0" "bi\x0" "\xd" "\x0" ""	/* amd64_xor_membase_reg */
	"\x0" "bi\x0" "\xf" "\x0" ""	/* amd64_mul_membase_reg */
	"\x0" "b\x0" "\x0" "\x10" "\x0" ""	/* amd64_add_membase_imm */
	"\x0" "b\x0" "\x0" "\x10" "\x0" ""	/* amd64_sub_membase_imm */
	"\x0" "b\x0" "\x0" "\xd" "\x0" ""	/* amd64_and_membase_imm */
	"\x0" "b\x0" "\x0" "\xd" "\x0" ""	/* amd64_or_membase_imm */
	"\x0" "b\x0" "\x0" "\xd" "\x0" ""	/* amd64_xor_membase_imm */
	"iib\x0" "\xe" "1"	/* amd64_add_reg_membase */
	"iib\x0" "\xe" "1"	/* amd64_sub_reg_membase */
	"iib\x0" "\xe" "1"	/* amd64_and_reg_membase */
	"iib\x0" "\xe" "1"	/* amd64_or_reg_membase */
	"iib\x0" "\xe" "1"	/* amd64_xor_reg_membase */
	"iii\x0" "\xa" "\x0" ""	/* amd64_loadi8_memindex */
	"\x0" "\x0" "\x0" "\x0" "\x10" "\x0" ""	/* amd64_save_sp_to_lmf */
	"i\x0" "\x0" "\x0" "\x20" "\x0" ""	/* get_last_error */
	"\x0" "i\x0" "\x0" "\x80" "\x0" ""	/* fill_prof_call_ctx */
};

const guint16 mono_amd64_desc_idx [] = {
	0,	/* load */
	0,	/* ldaddr */
	0,	/* store */
	6,	/* nop */
	12,	/* hard_nop */
	18,	/* relaxed_nop */
	0,	/* phi */
	0,	/* fphi */
	0,	/* vphi */
	24,	/* compare */
	30,	/* compare_imm */
	36,	/* fcompare */
	42,	/* rcompare */
	48,	/* lcompare */
	54,	/* icompare */
	60,	/* icompare_imm */
	66,	/* lcompare_imm */
	0,	/* local */
	0,	/* arg */
	0,	/* gsharedvt_local */
	0,	/* gsharedvt_arg_regoffset */
	0,	/* outarg_vt */
	0,	/* outarg_vtretaddr */
	0,	/* setret */
	0,	/* setfret */
	0,	/* setlret */
	72,	/* localloc */
	78,	/* localloc_imm */
	84,	/* checkthis */
	90,	/* seq_point */
	96,	/* il_seq_point */
	0,	/* implicit_exception */
	102,	/* voidcall */
	108,	/* voidcall_reg */
	114,	/* voidcall_membase */
	120,	/* call */
	126,	/* call_reg */
	132,	/* call_membase */
	138,	/* fcall */
	144,	/* fcall_reg */
	150,	/* fcall_membase */
	156,	/* rcall */
	162,	/* rcall_reg */
	168,	/* rcall_membase */
	174,	/* lcall */
	180,	/* lcall_reg */
	186,	/* lcall_membase */
	192,	/* vcall */
	198,	/* vcall_reg */
	204,	/* vcall_membase */
	210,	/* vcall2 */
	216,	/* vcall2_reg */
	222,	/* vcall2_membase */
	228,	/* dyn_call */
	234,	/* iconst */
	240,	/* i8const */
	246,	/* r4const */
	252,	/* r8const */
	258,	/* dummy_iconst */
	0,	/* dummy_i8const */
	264,	/* dummy_r8const */
	0,	/* dummy_r4const */
	0,	/* dummy_vzero */
	0,	/* regvar */
	0,	/* regoffset */
	0,	/* vtarg_addr */
	270,	/* label */
	0,	/* switch */
	276,	/* throw */
	282,	/* rethrow */
	288,	/* oparglist */
	294,	/* store_membase_reg */
	300,	/* storei1_membase_reg */
	306,	/* storei2_membase_reg */
	312,	/* storei4_membase_reg */
	318,	/* storei8_membase_reg */
	324,	/* storer4_membase_reg */
	330,	/* storer8_membase_reg */
	336,	/* storex_membase_reg */
	342,	/* storex_aligned_membase_reg */
	348,	/* storex_nta_membase_reg */
	354,	/* store_membase_imm */
	360,	/* storei1_membase_imm */
	366,	/* storei2_membase_imm */
	372,	/* storei4_membase_imm */
	378,	/* storei8_membase_imm */
	384,	/* storex_membase */
	0,	/* storev_membase */
	390,	/* load_membase */
	396,	/* loadi1_membase */
	402,	/* loadu1_membase */
	408,	/* loadi2_membase */
	414,	/* loadu2_membase */
	420,	/* loadi4_membase */
	426,	/* loadu4_membase */
	432,	/* loadi8_membase */
	438,	/* loadr4_membase */
	444,	/* loadr8_membase */
	450,	/* loadx_membase */
	456,	/* loadx_aligned_membase */
	0,	/* loadv_membase */
	0,	/* load_memindex */
	0,	/* loadi1_memindex */
	0,	/* loadu1_memindex */
	0,	/* loadi2_memindex */
	0,	/* loadu2_memindex */
	0,	/* loadi4_memindex */
	0,	/* loadu4_memindex */
	0,	/* loadi8_memindex */
	0,	/* loadr4_memindex */
	0,	/* loadr8_memindex */
	0,	/* store_memindex */
	0,	/* storei1_memindex */
	0,	/* storei2_memindex */
	0,	/* storei4_memindex */
	0,	/* storei8_memindex */
	0,	/* storer4_memindex */
	0,	/* storer8_memindex */
	462,	/* load_mem */
	468,	/* loadu1_mem */
	474,	/* loadu2_mem */
	480,	/* loadi4_mem */
	486,	/* loadu4_mem */
	492,	/* loadi8_mem */
	0,	/* store_mem_imm */
	498,	/* move */
	0,	/* lmove */
	504,	/* fmove */
	0,	/* vmove */
	510,	/* rmove */
	516,	/* move_f_to_i4 */
	522,	/* move_i4_to_f */
	528,	/* move_f_to_i8 */
	534,	/* move_i8_to_f */
	0,	/* vzero */
	540,	/* add_imm */
	546,	/* sub_imm */
	552,	/* mul_imm */
	0,	/* div_imm */
	0,	/* div_un_imm */
	0,	/* rem_imm */
	0,	/* rem_un_imm */
	558,	/* and_imm */
	564,	/* or_imm */
	570,	/* xor_imm */
	576,	/* shl_imm */
	582,	/* shr_imm */
	588,	/* shr_un_imm */
	594,	/* br */
	0,	/* jmp */
	600,	/* tailcall */
	606,	/* break */
	612,	/* ceq */
	618,	/* cgt */
	624,	/* cgt.un */
	630,	/* clt */
	636,	/* clt.un */
	642,	/* cond_exc_eq */
	648,	/* cond_exc_ge */
	654,	/* cond_exc_gt */
	660,	/* cond_exc_le */
	666,	/* cond_exc_lt */
	672,	/* cond_exc_ne_un */
	678,	/* cond_exc_ge_un */
	684,	/* cond_exc_gt_un */
	690,	/* cond_exc_le_un */
	696,	/* cond_exc_lt_un */
	702,	/* cond_exc_ov */
	708,	/* cond_exc_no */
	714,	/* cond_exc_c */
	720,	/* cond_exc_nc */
	726,	/* cond_exc_ieq */
	732,	/* cond_exc_ige */
	738,	/* cond_exc_igt */
	744,	/* cond_exc_ile */
	750,	/* cond_exc_ilt */
	756,	/* cond_exc_ine_un */
	762,	/* cond_exc_ige_un */
	768,	/* cond_exc_igt_un */
	774,	/* cond_exc_ile_un */
	780,	/* cond_exc_ilt_un */
	786,	/* cond_exc_iov */
	792,	/* cond_exc_ino */
	798,	/* cond_exc_ic */
	804,	/* cond_exc_inc */
	810,	/* long_add */
	816,	/* long_sub */
	822,	/* long_mul */
	828,	/* long_div */
	834,	/* long_div_un */
	840,	/* long_rem */
	846,	/* long_rem_un */
	852,	/* long_and */
	858,	/* long_or */
	864,	/* long_xor */
	870,	/* long_shl */
	876,	/* long_shr */
	882,	/* long_shr_un */
	888,	/* long_neg */
	894,	/* long_not */
	900,	/* long_conv_to_i1 */
	906,	/* long_conv_to_i2 */
	912,	/* long_conv_to_i4 */
	918,	/* long_conv_to_i8 */
	924,	/* long_conv_to_r4 */
	930,	/* long_conv_to_r8 */
	936,	/* long_conv_to_u4 */
	942,	/* long_conv_to_u8 */
	948,	/* long_conv_to_u2 */
	954,	/* long_conv_to_u1 */
	0,	/* long_conv_to_i */
	0,	/* long_conv_to_ovf_i */
	0,	/* long_conv_to_ovf_u */
	0,	/* long_add_ovf */
	0,	/* long_add_ovf_un */
	960,	/* long_mul_ovf */
	966,	/* long_mul_ovf_un */
	0,	/* long_sub_ovf */
	0,	/* long_sub_ovf_un */
	0,	/* long_conv_to_ovf_i1_un */
	0,	/* long_conv_to_ovf_i2_un */
	972,	/* long_conv_to_ovf_i4_un */
	0,	/* long_conv_to_ovf_i8_un */
	0,	/* long_conv_to_ovf_u1_un */
	0,	/* long_conv_to_ovf_u2_un */
	0,	/* long_conv_to_ovf_u4_un */
	0,	/* long_conv_to_ovf_u8_un */
	0,	/* long_conv_to_ovf_i_un */
	0,	/* long_conv_to_ovf_u_un */
	0,	/* long_conv_to_ovf_i1 */
	0,	/* long_conv_to_ovf_u1 */
	0,	/* long_conv_to_ovf_i2 */
	0,	/* long_conv_to_ovf_u2 */
	0,	/* long_conv_to_ovf_i4 */
	978,	/* long_conv_to_ovf_u4 */
	0,	/* long_conv_to_ovf_i8 */
	0,	/* long_conv_to_ovf_u8 */
	984,	/* long_ceq */
	990,	/* long_cgt */
	996,	/* long_cgt_un */
	1002,	/* long_clt */
	1008,	/* long_clt_un */
	1014,	/* long_conv_to_r_un */
	0,	/* long_conv_to_u */
	1020,	/* long_add_imm */
	1026,	/* long_sub_imm */
	1032,	/* long_mul_imm */
	1038,	/* long_and_imm */
	1044,	/* long_or_imm */
	1050,	/* long_xor_imm */
	1056,	/* long_shl_imm */
	1062,	/* long_shr_imm */
	1068,	/* long_shr_un_imm */
	0,	/* long_div_imm */
	0,	/* long_div_un_imm */
	0,	/* long_rem_imm */
	0,	/* long_rem_un_imm */
	1074,	/* long_beq */
	1080,	/* long_bge */
	1086,	/* long_bgt */
	1092,	/* long_ble */
	1098,	/* long_blt */
	1104,	/* long_bne_un */
	1110,	/* long_bge_un */
	1116,	/* long_bgt_un */
	1122,	/* long_ble_un */
	1128,	/* long_blt_un */
	0,	/* long_conv_to_r8_2 */
	0,	/* long_conv_to_r4_2 */
	0,	/* long_conv_to_r_un_2 */
	0,	/* long_conv_to_ovf_i4_2 */
	1134,	/* int_add */
	1140,	/* int_sub */
	1146,	/* int_mul */
	1152,	/* int_div */
	1158,	/* int_div_un */
	1164,	/* int_rem */
	1170,	/* int_rem_un */
	1176,	/* int_and */
	1182,	/* int_or */
	1188,	/* int_xor */
	1194,	/* int_shl */
	1200,	/* int_shr */
	1206,	/* int_shr_un */
	1212,	/* int_neg */
	1218,	/* int_not */
	1224,	/* int_conv_to_i1 */
	1230,	/* int_conv_to_i2 */
	1236,	/* int_conv_to_i4 */
	1242,	/* int_conv_to_i8 */
	1248,	/* int_conv_to_r4 */
	1254,	/* int_conv_to_r8 */
	1260,	/* int_conv_to_u4 */
	1266,	/* int_conv_to_u8 */
	0,	/* int_conv_to_r_un */
	1272,	/* int_conv_to_u */
	1278,	/* int_conv_to_u2 */
	1284,	/* int_conv_to_u1 */
	1290,	/* int_conv_to_i */
	0,	/* int_conv_to_ovf_i */
	0,	/* int_conv_to_ovf_u */
	0,	/* int_add_ovf */
	0,	/* int_add_ovf_un */
	1296,	/* int_mul_ovf */
	1302,	/* int_mul_ovf_un */
	0,	/* int_sub_ovf */
	0,	/* int_sub_ovf_un */
	0,	/* int_conv_to_ovf_i1_un */
	0,	/* int_conv_to_ovf_i2_un */
	0,	/* int_conv_to_ovf_i4_un */
	0,	/* int_conv_to_ovf_i8_un */
	0,	/* int_conv_to_ovf_u1_un */
	0,	/* int_conv_to_ovf_u2_un */
	0,	/* int_conv_to_ovf_u4_un */
	0,	/* int_conv_to_ovf_u8_un */
	0,	/* int_conv_to_ovf_i_un */
	0,	/* int_conv_to_ovf_u_un */
	0,	/* int_conv_to_ovf_i1 */
	0,	/* int_conv_to_ovf_u1 */
	0,	/* int_conv_to_ovf_i2 */
	0,	/* int_conv_to_ovf_u2 */
	0,	/* int_conv_to_ovf_i4 */
	0,	/* int_conv_to_ovf_u4 */
	0,	/* int_conv_to_ovf_i8 */
	0,	/* int_conv_to_ovf_u8 */
	1308,	/* int_adc */
	1314,	/* int_adc_imm */
	1320,	/* int_sbb */
	1326,	/* int_sbb_imm */
	1332,	/* int_addcc */
	1338,	/* int_subcc */
	1344,	/* int_add_imm */
	1350,	/* int_sub_imm */
	1356,	/* int_mul_imm */
	1362,	/* int_div_imm */
	1368,	/* int_div_un_imm */
	0,	/* int_rem_imm */
	1374,	/* int_rem_un_imm */
	1380,	/* int_and_imm */
	1386,	/* int_or_imm */
	1392,	/* int_xor_imm */
	1398,	/* int_shl_imm */
	1404,	/* int_shr_imm */
	1410,	/* int_shr_un_imm */
	1416,	/* int_ceq */
	1422,	/* int_cgt */
	1428,	/* int_cgt_un */
	1434,	/* int_clt */
	1440,	/* int_clt_un */
	1446,	/* int_cneq */
	1452,	/* int_cge */
	1458,	/* int_cle */
	1464,	/* int_cge_un */
	1470,	/* int_cle_un */
	1476,	/* int_beq */
	1482,	/* int_bge */
	1488,	/* int_bgt */
	1494,	/* int_ble */
	1500,	/* int_blt */
	1506,	/* int_bne_un */
	1512,	/* int_bge_un */
	1518,	/* int_bgt_un */
	1524,	/* int_ble_un */
	1530,	/* int_blt_un */
	1536,	/* float_beq */
	1542,	/* float_bge */
	1548,	/* float_bgt */
	1554,	/* float_ble */
	1560,	/* float_blt */
	1566,	/* float_bne_un */
	1572,	/* float_bge_un */
	1578,	/* float_bgt_un */
	1584,	/* float_ble_un */
	1590,	/* float_blt_un */
	0,	/* r4_beq */
	0,	/* r4_bge */
	0,	/* r4_bgt */
	0,	/* r4_ble */
	0,	/* r4_blt */
	0,	/* r4_bne_un */
	0,	/* r4_bge_un */
	0,	/* r4_bgt_un */
	0,	/* r4_ble_un */
	0,	/* r4_blt_un */
	1596,	/* float_add */
	1602,	/* float_sub */
	1608,	/* float_mul */
	1614,	/* float_div */
	1620,	/* float_div_un */
	1626,	/* float_rem */
	1632,	/* float_rem_un */
	1638,	/* r4_add */
	1644,	/* r4_sub */
	1650,	/* r4_mul */
	1656,	/* r4_div */
	0,	/* r4_div_un */
	0,	/* r4_rem */
	0,	/* r4_rem_un */
	1662,	/* float_neg */
	1668,	/* float_not */
	1674,	/* float_conv_to_i1 */
	1680,	/* float_conv_to_i2 */
	1686,	/* float_conv_to_i4 */
	1692,	/* float_conv_to_i8 */
	1698,	/* float_conv_to_r4 */
	0,	/* float_conv_to_r8 */
	1704,	/* float_conv_to_u4 */
	1710,	/* float_conv_to_u8 */
	1716,	/* r4_neg */
	0,	/* r4_not */
	1722,	/* r4_conv_to_i1 */
	1728,	/* r4_conv_to_i2 */
	1734,	/* r4_conv_to_i4 */
	1740,	/* r4_conv_to_i8 */
	1746,	/* r4_conv_to_r4 */
	1752,	/* r4_conv_to_r8 */
	1758,	/* r4_conv_to_u4 */
	0,	/* r4_conv_to_u8 */
	1764,	/* float_conv_to_u2 */
	1770,	/* float_conv_to_u1 */
	1776,	/* float_conv_to_i */
	1782,	/* float_conv_to_ovf_i */
	1788,	/* float_conv_to_ovd_u */
	0,	/* float_add_ovf */
	0,	/* float_add_ovf_un */
	1794,	/* float_mul_ovf */
	0,	/* float_mul_ovf_un */
	0,	/* float_sub_ovf */
	0,	/* float_sub_ovf_un */
	0,	/* float_conv_to_ovf_i1_un */
	0,	/* float_conv_to_ovf_i2_un */
	0,	/* float_conv_to_ovf_i4_un */
	0,	/* float_conv_to_ovf_i8_un */
	0,	/* float_conv_to_ovf_u1_un */
	0,	/* float_conv_to_ovf_u2_un */
	0,	/* float_conv_to_ovf_u4_un */
	0,	/* float_conv_to_ovf_u8_un */
	0,	/* float_conv_to_ovf_i_un */
	0,	/* float_conv_to_ovf_u_un */
	0,	/* float_conv_to_ovf_i1 */
	0,	/* float_conv_to_ovf_u1 */
	0,	/* float_conv_to_ovf_i2 */
	0,	/* float_conv_to_ovf_u2 */
	0,	/* float_conv_to_ovf_i4 */
	0,	/* float_conv_to_ovf_u4 */
	0,	/* float_conv_to_ovf_i8 */
	0,	/* float_conv_to_ovf_u8 */
	1800,	/* float_ceq */
	1806,	/* float_cgt */
	1812,	/* float_cgt_un */
	1818,	/* float_clt */
	1824,	/* float_clt_un */
	1830,	/* float_cneq */
	1836,	/* float_cge */
	1842,	/* float_cle */
	1848,	/* float_ceq_membase */
	1854,	/* float_cgt_membase */
	1860,	/* float_cgt_un_membase */
	1866,	/* float_clt_membase */
	1872,	/* float_clt_un_membase */
	1878,	/* float_conv_to_u */
	1884,	/* ckfinite */
	1890,	/* r4_conv_to_u2 */
	1896,	/* r4_conv_to_u1 */
	0,	/* r4_conv_to_i */
	0,	/* r4_conv_to_ovf_i */
	0,	/* r4_conv_to_ovd_u */
	0,	/* r4_add_ovf */
	0,	/* r4_add_ovf_un */
	0,	/* r4_mul_ovf */
	0,	/* r4_mul_ovf_un */
	0,	/* r4_sub_ovf */
	0,	/* r4_sub_ovf_un */
	0,	/* r4_conv_to_ovf_i1_un */
	0,	/* r4_conv_to_ovf_i2_un */
	0,	/* r4_conv_to_ovf_i4_un */
	0,	/* r4_conv_to_ovf_i8_un */
	0,	/* r4_conv_to_ovf_u1_un */
	0,	/* r4_conv_to_ovf_u2_un */
	0,	/* r4_conv_to_ovf_u4_un */
	0,	/* r4_conv_to_ovf_u8_un */
	0,	/* r4_conv_to_ovf_i_un */
	0,	/* r4_conv_to_ovf_u_un */
	0,	/* r4_conv_to_ovf_i1 */
	0,	/* r4_conv_to_ovf_u1 */
	0,	/* r4_conv_to_ovf_i2 */
	0,	/* r4_conv_to_ovf_u2 */
	0,	/* r4_conv_to_ovf_i4 */
	0,	/* r4_conv_to_ovf_u4 */
	0,	/* r4_conv_to_ovf_i8 */
	0,	/* r4_conv_to_ovf_u8 */
	1902,	/* r4_ceq */
	1908,	/* r4_cgt */
	1914,	/* r4_cgt_un */
	1920,	/* r4_clt */
	1926,	/* r4_clt_un */
	1932,	/* r4_cneq */
	1938,	/* r4_cge */
	1944,	/* r4_cle */
	0,	/* float_getlow32 */
	0,	/* float_gethigh32 */
	1950,	/* jump_table */
	1956,	/* aot_const */
	0,	/* patch_info */
	0,	/* got_entry */
	1962,	/* call_handler */
	1968,	/* start_handler */
	1974,	/* endfilter */
	1980,	/* endfinally */
	1986,	/* get_ex_obj */
	0,	/* bigmul */
	0,	/* bigmul_un */
	1992,	/* int_min_un */
	1998,	/* int_max_un */
	2004,	/* long_min_un */
	2010,	/* long_max_un */
	0,	/* min */
	0,	/* max */
	2016,	/* int_min */
	2022,	/* int_max */
	2028,	/* long_min */
	2034,	/* long_max */
	2040,	/* adc */
	2046,	/* adc_imm */
	2052,	/* sbb */
	2058,	/* sbb_imm */
	2064,	/* addcc */
	0,	/* addcc_imm */
	2070,	/* subcc */
	0,	/* subcc_imm */
	2076,	/* br_reg */
	2082,	/* sext_i1 */
	2088,	/* sext_i2 */
	2094,	/* sext_i4 */
	0,	/* zext_i1 */
	0,	/* zext_i2 */
	2100,	/* zext_i4 */
	0,	/* cne */
	0,	/* trunc_i4 */
	0,	/* add_ovf_carry */
	0,	/* sub_ovf_carry */
	0,	/* add_ovf_un_carry */
	0,	/* sub_ovf_un_carry */
	2106,	/* laddcc */
	2112,	/* lsubcc */
	2118,	/* sin */
	2124,	/* cos */
	2130,	/* abs */
	2136,	/* tan */
	2142,	/* atan */
	2148,	/* sqrt */
	0,	/* round */
	0,	/* strlen */
	0,	/* newarr */
	0,	/* ldlen */
	0,	/* bounds_check */
	0,	/* isinst */
	0,	/* castclass */
	0,	/* getldelema2 */
	0,	/* memcpy */
	0,	/* memset */
	0,	/* save_lmf */
	0,	/* restore_lmf */
	2154,	/* card_table_wbarrier */
	2160,	/* tls_get */
	0,	/* tls_get_reg */
	2166,	/* tls_set */
	0,	/* tls_set_reg */
	0,	/* load_gotaddr */
	2172,	/* dummy_use */
	2178,	/* dummy_store */
	2184,	/* not_reached */
	2190,	/* not_null */
	2196,	/* addps */
	2202,	/* divps */
	2208,	/* mulps */
	2214,	/* subps */
	2220,	/* maxps */
	2226,	/* minps */
	2232,	/* compps */
	2238,	/* andps */
	2244,	/* andnps */
	2250,	/* orps */
	2256,	/* xorps */
	2262,	/* haddps */
	2268,	/* hsubps */
	2274,	/* addsubps */
	2280,	/* dupps_low */
	2286,	/* dupps_high */
	2292,	/* rsqrtps */
	2298,	/* sqrtps */
	2304,	/* rcpps */
	2310,	/* pshufflew_high */
	2316,	/* pshufflew_low */
	2322,	/* pshuffled */
	2328,	/* shufps */
	2334,	/* shufpd */
	2340,	/* addpd */
	2346,	/* divpd */
	2352,	/* mulpd */
	2358,	/* subpd */
	2364,	/* maxpd */
	2370,	/* minpd */
	2376,	/* comppd */
	2382,	/* andpd */
	2388,	/* andnpd */
	2394,	/* orpd */
	2400,	/* xorpd */
	2406,	/* haddpd */
	2412,	/* hsubpd */
	2418,	/* addsubpd */
	2424,	/* duppd */
	2430,	/* sqrtpd */
	2436,	/* extract_mask */
	2442,	/* pand */
	2448,	/* por */
	2454,	/* pxor */
	2460,	/* paddb */
	2466,	/* paddw */
	2472,	/* paddd */
	2478,	/* paddq */
	2484,	/* psubb */
	2490,	/* psubw */
	2496,	/* psubd */
	2502,	/* psubq */
	2508,	/* pmaxb_un */
	2514,	/* pmaxw_un */
	2520,	/* pmaxd_un */
	2526,	/* pmaxb */
	2532,	/* pmaxw */
	2538,	/* pmaxd */
	2544,	/* pavgb_un */
	2550,	/* pavgw_un */
	2556,	/* pminb_un */
	2562,	/* pminw_un */
	2568,	/* pmind_un */
	2574,	/* pminb */
	2580,	/* pminw */
	2586,	/* pmind */
	2592,	/* pcmpeqb */
	2598,	/* pcmpeqw */
	2604,	/* pcmpeqd */
	2610,	/* pcmpeqq */
	2616,	/* pcmpgtb */
	2622,	/* pcmpgtw */
	2628,	/* pcmpgtd */
	2634,	/* pcmpgtq */
	2640,	/* psumabsdiff */
	2646,	/* unpack_lowb */
	2652,	/* unpack_loww */
	2658,	/* unpack_lowd */
	2664,	/* unpack_lowq */
	2670,	/* unpack_lowps */
	2676,	/* unpack_lowpd */
	2682,	/* unpack_highb */
	2688,	/* unpack_highw */
	2694,	/* unpack_highd */
	2700,	/* unpack_highq */
	2706,	/* unpack_highps */
	2712,	/* unpack_highpd */
	2718,	/* packw */
	2724,	/* packd */
	2730,	/* packw_un */
	2736,	/* packd_un */
	2742,	/* paddb_sat */
	2748,	/* paddb_sat_un */
	2754,	/* paddw_sat */
	2760,	/* paddw_sat_un */
	2766,	/* psubb_sat */
	2772,	/* psubb_sat_un */
	2778,	/* psubw_sat */
	2784,	/* psubw_sat_un */
	2790,	/* pmulw */
	2796,	/* pmuld */
	2802,	/* pmulq */
	2808,	/* pmul_high_un */
	2814,	/* pmul_high */
	2820,	/* pshrw */
	2826,	/* pshrw_reg */
	2832,	/* psarw */
	2838,	/* psarw_reg */
	2844,	/* pshlw */
	2850,	/* pshlw_reg */
	2856,	/* pshrd */
	2862,	/* pshrd_reg */
	2868,	/* pshrq */
	2874,	/* pshrq_reg */
	2880,	/* psard */
	2886,	/* psard_reg */
	2892,	/* pshld */
	2898,	/* pshld_reg */
	2904,	/* pshlq */
	2910,	/* pshlq_reg */
	2916,	/* extract_i4 */
	2922,	/* iconv_to_r4_raw */
	2928,	/* extract_i2 */
	2934,	/* extract_u2 */
	2940,	/* extract_i1 */
	2946,	/* extract_u1 */
	2952,	/* extract_r8 */
	2958,	/* extract_i8 */
	0,	/* insert_i1 */
	0,	/* insert_i4 */
	0,	/* insert_i8 */
	0,	/* insert_r4 */
	0,	/* insert_r8 */
	2964,	/* insert_i2 */
	2970,	/* extractx_u2 */
	2976,	/* insertx_u1_slow */
	2982,	/* insertx_i4_slow */
	2988,	/* insertx_r4_slow */
	2994,	/* insertx_r8_slow */
	3000,	/* insertx_i8_slow */
	3006,	/* fconv_to_r8_x */
	3012,	/* xconv_r8_to_i4 */
	3018,	/* iconv_to_x */
	0,	/* expand_i1 */
	3024,	/* expand_i2 */
	3030,	/* expand_i4 */
	3036,	/* expand_r4 */
	3042,	/* expand_i8 */
	3048,	/* expand_r8 */
	3054,	/* prefetch_membase */
	3060,	/* cvtdq2pd */
	3066,	/* cvtdq2ps */
	3072,	/* cvtpd2dq */
	3078,	/* cvtpd2ps */
	3084,	/* cvtps2dq */
	3090,	/* cvtps2pd */
	3096,	/* cvttpd2dq */
	3102,	/* cvttps2dq */
	0,	/* dpps */
	3108,	/* xmove */
	3114,	/* xzero */
	3120,	/* xones */
	0,	/* xphi */
	3126,	/* memory_barrier */
	3132,	/* atomic_load_i1 */
	3138,	/* atomic_load_i2 */
	3144,	/* atomic_load_i4 */
	3150,	/* atomic_load_i8 */
	3156,	/* atomic_load_u1 */
	3162,	/* atomic_load_u2 */
	3168,	/* atomic_load_u4 */
	3174,	/* atomic_load_u8 */
	3180,	/* atomic_load_r4 */
	3186,	/* atomic_load_r8 */
	3192,	/* atomic_store_i1 */
	3198,	/* atomic_store_i2 */
	3204,	/* atomic_store_i4 */
	3210,	/* atomic_store_i8 */
	3216,	/* atomic_store_u1 */
	3222,	/* atomic_store_u2 */
	3228,	/* atomic_store_u4 */
	3234,	/* atomic_store_u8 */
	3240,	/* atomic_store_r4 */
	3246,	/* atomic_store_r8 */
	3252,	/* atomic_add_i4 */
	3258,	/* atomic_add_i8 */
	3264,	/* atomic_exchange_i4 */
	3270,	/* atomic_exchange_i8 */
	3276,	/* atomic_cas_i4 */
	3282,	/* atomic_cas_i8 */
	3288,	/* cmov_ieq */
	3294,	/* cmov_ige */
	3300,	/* cmov_igt */
	3306,	/* cmov_ile */
	3312,	/* cmov_ilt */
	3318,	/* cmov_ine_un */
	3324,	/* cmov_ige_un */
	3330,	/* cmov_igt_un */
	3336,	/* cmov_ile_un */
	3342,	/* cmov_ilt_un */
	3348,	/* cmov_leq */
	3354,	/* cmov_lge */
	3360,	/* cmov_lgt */
	3366,	/* cmov_lle */
	3372,	/* cmov_llt */
	3378,	/* cmov_lne_un */
	3384,	/* cmov_lge_un */
	3390,	/* cmov_lgt_un */
	3396,	/* cmov_lle_un */
	3402,	/* cmov_llt_un */
	3408,	/* liverange_start */
	3414,	/* liverange_end */
	3420,	/* gc_liveness_def */
	3426,	/* gc_liveness_use */
	3432,	/* gc_spill_slot_liveness_def */
	3438,	/* gc_param_slot_liveness_def */
	3444,	/* gc_safe_point */
	3450,	/* generic_class_init */
	3456,	/* x86_test_null */
	3462,	/* x86_compare_membase_reg */
	3468,	/* x86_compare_membase_imm */
	0,	/* x86_compare_mem_imm */
	3474,	/* x86_compare_membase8_imm */
	3480,	/* x86_compare_reg_membase */
	3486,	/* x86_inc_reg */
	3492,	/* x86_inc_membase */
	3498,	/* x86_dec_reg */
	3504,	/* x86_dec_membase */
	3510,	/* x86_add_membase_imm */
	3516,	/* x86_sub_membase_imm */
	3522,	/* x86_and_membase_imm */
	3528,	/* x86_or_membase_imm */
	3534,	/* x86_xor_membase_imm */
	3540,	/* x86_add_membase_reg */
	3546,	/* x86_sub_membase_reg */
	3552,	/* x86_and_membase_reg */
	3558,	/* x86_or_membase_reg */
	3564,	/* x86_xor_membase_reg */
	3570,	/* x86_mul_membase_reg */
	3576,	/* x86_add_reg_membase */
	3582,	/* x86_sub_reg_membase */
	3588,	/* x86_mul_reg_membase */
	3594,	/* x86_and_reg_membase */
	3600,	/* x86_or_reg_membase */
	3606,	/* x86_xor_reg_membase */
	3612,	/* x86_push_membase */
	3618,	/* x86_push_imm */
	3624,	/* x86_push */
	3630,	/* x86_push_obj */
	0,	/* x86_push_got_entry */
	3636,	/* x86_lea */
	3642,	/* x86_lea_membase */
	3648,	/* x86_xchg */
	3654,	/* x86_fpop */
	0,	/* x86_fp_load_i8 */
	0,	/* x86_fp_load_i4 */
	3660,	/* x86_seteq_membase */
	0,	/* x86_setne_membase */
	0,	/* x86_fxch */
	3666,	/* amd64_test_null */
	3672,	/* amd64_set_xmmreg_r4 */
	3678,	/* amd64_set_xmmreg_r8 */
	3684,	/* amd64_icompare_membase_reg */
	3690,	/* amd64_icompare_membase_imm */
	3696,	/* amd64_icompare_reg_membase */
	3702,	/* amd64_compare_membase_reg */
	3708,	/* amd64_compare_membase_imm */
	3714,	/* amd64_compare_reg_membase */
	3720,	/* amd64_add_membase_reg */
	3726,	/* amd64_sub_membase_reg */
	3732,	/* amd64_and_membase_reg */
	3738,	/* amd64_or_membase_reg */
	3744,	/* amd64_xor_membase_reg */
	3750,	/* amd64_mul_membase_reg */
	3756,	/* amd64_add_membase_imm */
	3762,	/* amd64_sub_membase_imm */
	3768,	/* amd64_and_membase_imm */
	3774,	/* amd64_or_membase_imm */
	3780,	/* amd64_xor_membase_imm */
	0,	/* amd64_mul_membase_imm */
	3786,	/* amd64_add_reg_membase */
	3792,	/* amd64_sub_reg_membase */
	3798,	/* amd64_and_reg_membase */
	3804,	/* amd64_or_reg_membase */
	3810,	/* amd64_xor_reg_membase */
	0,	/* amd64_mul_reg_membase */
	3816,	/* amd64_loadi8_memindex */
	3822,	/* amd64_save_sp_to_lmf */
	0,	/* llvm_outarg_vt */
	0,	/* objc_get_selector */
	0,	/* get_sp */
	0,	/* set_sp */
	3828,	/* get_last_error */
	3834,	/* fill_prof_call_ctx */
};

